import Head from "next/head";
import Header from "../components/Header";
import Banner from "../components/Banner";
import SmallCard from "../components/SmallCard";
import MediumCard from "../components/MediumCard";
import LargeCard from "../components/LargeCard";
import Footer from "../components/Footer";
import BottomNav from "../components/BottomNav";

export default function Home({ exploreData, cardData }) {
  return (
    <>
      <div className="dark:bg-dark">
        <Head>
          <title>Roomsy: Vacation rentals, Cabins, Beach houses </title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <BottomNav />
        <Header />
        <Banner />

        <main className="max-w-7xl mx-auto px-8 sm:px-16">
          <section className="pt-6">
            <h2 className="text-3xl font-pop sm:text-4xl font-semibold pb-5">
              Explore Nearby
            </h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
              {exploreData?.map((item) => (
                <SmallCard
                  key={item.img}
                  img={item.img}
                  location={item.location}
                  distance={item.distance}
                />
              ))}
            </div>
          </section>
          <section>
            <h2 className="text-3xl font-pop sm:text-4xl font-semibold py-9">
              Live anywhere
            </h2>
            <div className="flex overflow-x-scroll overflow-y-hidden space-x-3 scrollbar-hide items-center p-3 -ml-3">
              {cardData?.map((item) => (
                <MediumCard key={item.img} img={item.img} title={item.title} />
              ))}
            </div>
          </section>
          <LargeCard
            img="https://links.papareact.com/4cj"
            title="The Greatest Outdoors"
            description="Wishlist curated by Roomsy"
            buttonTxt="Get Inspired"
          />
        </main>
        <Footer />
      </div>
    </>
  );
}

export async function getStaticProps() {
  const exploreData = await fetch("https://jsonkeeper.com/b/6GGE").then((res) =>
    res.json()
  );
  // console.log(exploreData);

  const cardData = await fetch("https://jsonkeeper.com/b/OOMU").then((res) =>
    res.json()
  );

  return {
    props: {
      exploreData,
      cardData,
    },
  };
}
